# Generated by Django 3.0.3 on 2020-02-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200212_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='small_description',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
