# Generated by Django 3.0.3 on 2020-02-12 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_small_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='small_description',
        ),
    ]
