# Generated by Django 3.0.3 on 2020-02-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200222_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo_images', verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='home',
            name='slider',
            field=models.ImageField(blank=True, null=True, upload_to='slider_images', verbose_name='slider'),
        ),
    ]
