# Generated by Django 3.0.3 on 2020-02-10 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200210_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
            preserve_default=False,
        ),
    ]
