# Generated by Django 3.0.3 on 2020-02-21 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_itemorder_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemorder',
            options={'verbose_name': 'Елемент', 'verbose_name_plural': 'Елемент'},
        ),
    ]
